language: python
python: '2.7'
branches:
  only:
  - master
before_install:
- pip install --upgrade pip
install:
- pip install pelican
- pip install Markdown
- pip install typogrify
#- pip install linkchecker

before_script:
- git config --global user.name 'Lukas Woodtli (travis-ci)'
- git config --global user.email woodtli.lukas@gmail.com

- bash ./clone_theme.sh

script:
- rm -rf output/
- make html
- bash ./publish_to_ghp.sh
#- linkchecker http://lukaswoodtli.github.io/Rezepte


env:
  global:
    secure: wsc54Veoi4TdX2Med8HJf4DThR1b3hElOIMwLfMXieemH2o7dFCuvO/I9eLlDAzJulEngUHemAPpagu1brW6Q5YkvSQu/hNOo5HStSc+9D0QJ6UVN7/f7E/6v3TWSwgEGsfQGuaF2FXz6B7yRlvPHcaypykRdfrkqXDTGZC46PcEDDzHIqHsMCnw6PEmtgTwJLHol+pKCakGuQuCloA5aE1fqE1M6LNW4IUoLtHR00SihXI3jWs3a6JQaRjsU487zn0LAgm2MKMhqMMI5DCm/aXmdQSJ4qxBL/rmIjogJd/FUPOGVj/6N8zy4KVZJv7zs6JM9PkZVJP40MQ47A6MDNtqx1SZUB6Sxjn+yd3TUgQSNH2HUBG/7ePR0vHzVi3IXmq1bxzBMFYxcxJNDekKlQlN54SaodH4SPME0+Rs0HG715ib4xd3PMfKM50DCiYsc0I1MvcrI+dbw4i2GCs71NvFDF72mwIqaHpyDbuaSXFlPksRiVSFEoPD82A/NyB1UOmVZBQe2kU/8ETB4uah2VpLO+byvjvadooT6sqq4AwWd9rswxiOpVYV9I7ORRPakKu5IshtuhR9VMfCTB19US5iw/eB/P3vt+8Z2IfaM+czox/7/IhEFtimb8K6vCfWKUqW5F6yKLYq2+M7EqsOxD2zJP00ni4gO5sbUOFkuaE=
