name: Build and Deploy

on:
  pull_request:
    branches: 
     - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Clone Theme
      run: ./clone_theme.sh
    - name: Build Web Page
      run: make html
